services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_DB: "jiraiya"
      POSTGRES_USER: "jiraiya"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_tables:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jiraiya -d jiraiya" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/db_data
      o: bind
  db_tables:
    driver: local
    driver_opts:
      type: none
      device: ./data/db_tables
      o: bind

networks:
  postgres:
    driver: bridge
